@startuml
class OracLib.BaseQuote {
# Label quoteTextArea
# void initialize()
# void loadRandomQuote()
# void closeQuoteView()
- List<String> readQuotesFromTXT(String)
}
class OracLib.QuoteController {
- Label quoteTextArea
# void initialize()
# void closeQuoteView()
}
class OracLib.Main {
- {static} Stage window
- {static} Clip clip
- UserProfiles userProfiles
- BookProfiles bookProfiles
- {static} String currentUsername
+ {static} String getCurrentUsername()
+ {static} void setCurrentUsername(String)
+ UserProfiles getUserProfiles()
+ BookProfiles getBookProfiles()
+ void start(Stage)
+ void sceneToRegister(String,double,double)
+ void sceneToMenu(String,double,double,String)
+ void sceneToLogin(String,double,double)
+ void sceneToAdminView(String,double,double,String)
+ void sceneToProfile(String,double,double,String)
- void loadProfiles(String)
- void countProfiles(String)
- void loadBooks(String)
- void countBooks(String)
- void showErrorDialog(String)
+ {static} void main(String[])
}
class OracLib.RegisterController {
- TextField username
- TextField password
- TextField rePassword
- Label prompt
- MediaView mediaView
- Main main
+ void setMain(Main)
- void handleRegister(ActionEvent)
- void onReturn(ActionEvent)
- boolean isNameExists(String)
- boolean isNotValidString(String)
- void showAlert(String)
- void onExit()
}
class OracLib.PDFViewFX.PDFBoxDocument {
- PDDocument document
+ int getNumberOfPages()
+ boolean isLandscape(int)
+ Pageable getPageable()
+ BufferedImage renderPage(int,float)
+ List<PDFView.SearchResult> getSearchResults(String)
+ void close()
- Rectangle2D calculateMarkerPosition(String,String,List<TextPosition>)
- int calculateTextPositionStartIndex(String,String,List<TextPosition>)
}
class OracLib.UserProfileController {
- Button profilePicButton
- Button nameButton
- Button bioButton
- Button ageButton
- TextField inputUsername
- TextField inputAge
- TextField inputBio
- ImageView pictureView
- Label editMode
- Label statusLabel
- Label nameLabel
- Label ageLabel
- Label bioLabel
- TableView<Books> favoriteTableView
- TableColumn<Books,String> favTitleColumn
- TableColumn<Books,String> favAuthorColumn
- TableColumn<Books,String> favDatePublishedColumn
- TableColumn<Books,String> favGenreColumn
- TableColumn<Books,String> favBookCodeColumn
- Stage stage
- Main main
- String username
- String currentUserName
- UserProfiles userProfiles
- List<List<String>> profileInfo
+ void setMain(Main)
+ void setUsername(String)
+ void displayInfo(String)
+ void setStage(Stage)
+ void handleAccountEdit(ActionEvent)
+ void handleProfilePicChange(ActionEvent)
+ void handleNameChange(ActionEvent)
- void passwordConfirmation()
- boolean isValid(String,String)
+ void handleBioChange(ActionEvent)
+ void handleAgeChange(ActionEvent)
- void updateProfile(String,String)
- List<List<String>> readDatabase(File)
- void modifyProfile(int,String,String)
- List<Books> getUserBookData(String,String)
- void populateFavTableView(List<Books>)
- void handleFavBookClick(MouseEvent)
- void saveProfile(File)
- void handleReturn()
- void showErrorDialog(String)
}
class OracLib.LibraryController {
- Label title
- Label author
- Label description
- ImageView bookImageView
- Hyperlink link
- Main main
- Stage primaryStage
- String bookCode
- String bookTitle
+ void setMain(Main)
+ void setPrimaryStage(Stage)
+ void setBookCode(String)
+ void setBookData(Books)
+ void setBookTitle(String)
+ void setBookImage(String)
+ void handlePDF(ActionEvent)
- void handleFavoriteButton(ActionEvent)
- void replaceFirstFavoriteBook(UserData,String)
- UserProfiles readUserProfilesFromTXT(String)
- void saveUserProfilesToTXT(String,UserProfiles)
}
class OracLib.BookViewer {
- FileChooser chooser
- Main main
- String bookCode
- String title
+ void setBook(String)
+ void setTitle(String)
+ void openBook()
}
class OracLib.Books {
- String bookCode
- String title
- String author
- String yearPublished
- String genre
- String description
- String link
+ String getDescription()
+ void setDescription(String)
+ String getLink()
+ void setLink(String)
+ String getTitle()
+ void setTitle(String)
+ String getAuthor()
+ void setAuthor(String)
+ String getYearPublished()
+ void setYearPublished(String)
+ String getGenre()
+ void setGenre(String)
+ String getBookCode()
+ void setBookCode(String)
}
class OracLib.AdminViewController {
- Label editLabel
- Label nameLabel
- Label ageLabel
- Label bioLabel
- Label bookNameLabel
- Label bookAuthorLabel
- Label bookGenreLabel
- Label bookDescriptionLabel
- Label bookYearLabel
- Label statusChangeLabel
- TextField usernameField
- TextField passwordField
- TextField bioField
- TextField ageField
- TextField imageField
- TextField codeField
- TextField titleField
- TextField authorField
- TextField yearField
- TextField genreField
- TextField linkField
- TextField descriptionField
- TextField coverPhotoField
- TextField pdfNameField
- TextField bookInput
- TextField userInput
- ImageView bookImageView
- ImageView userImageView
- AnchorPane bookAdminView
- AnchorPane userAdminView
- Button saveChangesButton
- Button saveUserButton
- Button deleteUserNameButton
- Button profilePicture
- Button saveBookButton
- Button saveBookChanges
- Button deleteBookCodeButton
- Button coverPhotoButton
- Button pdfFileButton
- Button bookSearch
- Button userSearch
- Stage stage
- Main main
- String adminName
- String currentUserName
- String currentPassword
- String currentBookCode
- String currentImage
- FileInputStream currentInputStream
- UserProfiles userProfiles
- BookProfiles bookProfiles
- List<List<String>> profileInfo
- List<List<String>> bookInfo
~ TextFormatter<String> textFormatter
+ void setMain(Main)
+ void setUsername(String)
- void handleAddBook(ActionEvent)
- void handleEditBook(ActionEvent)
- void handleDeleteBook(ActionEvent)
- void handleAddUser(ActionEvent)
- void handleEditUser(ActionEvent)
- void handleDeleteUser(ActionEvent)
- void handleProfilePicture(ActionEvent)
- void handleCoverPhoto(ActionEvent)
- void handlePDFFile(ActionEvent)
- void displayBook(String)
- void displayInfo(String)
- void handleUserSearch(ActionEvent)
- void handleSaveUser(ActionEvent)
- void handleUserChanges(ActionEvent)
- void handleDelUser(ActionEvent)
- void handleBookSearch(ActionEvent)
- void handleNewBook(ActionEvent)
- void handleBookChanges(ActionEvent)
- void handleDelBook(ActionEvent)
- void updateBook(String)
- void updateProfile(String)
- List<List<String>> readDatabase(File)
- void modifyDatabase(int,String,String)
- void saveDatabase(File)
- void modifyBookDatabase(int,String,String)
- void saveBookDatabase(File)
- void clearUserFields()
- void clearUserDisplay()
- void clearBookFields()
- void clearBookDisplay()
- boolean isNameExists(String)
- boolean isBookExists(String)
- boolean isNotValidString(String)
- void loadProfiles(String)
- void countProfiles(String)
- void loadBooks(String)
- void countBooks(String)
- void showErrorDialog(String)
- void handleReturn(ActionEvent)
}
class OracLib.BookProfiles {
- int size
- Books[] book
+ int getSize()
+ void setSize(int)
+ Books getBook(int)
+ void setBook(Books,int)
+ int searchBook(String)
}
interface OracLib.LibraryView {
~ void setMain(Main)
~ void setBookCode(String)
~ void setBookData(Books)
~ void setBookTitle(String)
~ void setBookImage(String)
~ void setPrimaryStage(Stage)
}
class OracLib.MainController {
+ Button adminViewButton
- TableView<Books> libraryTableView
- TableColumn<Books,String> titleColumn
- TableColumn<Books,String> authorColumn
- TableColumn<Books,String> datePublishedColumn
- TableColumn<Books,String> genreColumn
- TableColumn<Books,String> bookCodeColumn
- TableView<Books> favoriteTableView
- TableColumn<Books,String> favTitleColumn
- TableColumn<Books,String> favAuthorColumn
- TableColumn<Books,String> favDatePublishedColumn
- TableColumn<Books,String> favGenreColumn
- TableColumn<Books,String> favBookCodeColumn
- TextField searchBar
- Button resetFields
- ImageView userProfile
- Main main
- String name
+ void setMain(Main)
+ void setProfile(String)
- void initialize()
- void handleSearchButton(ActionEvent)
- void handleClearReset(ActionEvent)
- void showRandomBook(ActionEvent)
- void showQuoteOfTheDay(ActionEvent)
- double calculateJaccardSimilarity(String,String)
- void populateTableView(List<Books>)
- void populateFavTableView(List<Books>)
- List<Books> readBookDataFromCSV(String)
- List<Books> getUserBookData(String,String)
- void handleBookClick(MouseEvent)
- void handleFavBookClick(MouseEvent)
- void handleProfile(ActionEvent)
- void retrieveProfilePicture(String)
- void handleAdminAccess(ActionEvent)
- void showErrorDialog(String)
- void onLogout(ActionEvent)
}
class OracLib.UserProfiles {
- List<UserData> users
+ List<UserData> getUsers()
+ void setUsers(List<UserData>)
+ void addUser(UserData)
+ int searchUser(String)
+ UserData getUser(int)
}
class OracLib.PDFViewFX.skins.PDFViewSkin {
- Executor EXECUTOR
- ObservableList<Integer> pdfFilePages
- BorderPane borderPane
- ListView<Integer> thumbnailListView
- ListView<PageSearchResult> searchResultListView
- Map<Integer,Image> imageCache
- SearchService searchService
- DoubleProperty requestedVValue
- PagerService pagerService
- ObservableList<PageSearchResult> pageSearchResults
- void maybeScrollTo(ListView<T>,T)
- void search()
- ToolBar createToolBar(PDFView)
- HBox createSearchNavigator()
+ void showNextSearchResult()
+ void showPreviousSearchResult()
- void updateMaximumValue(IntegerInputField)
- void updateCurrentPageNumber(PDFView,IntegerInputField)
- void updateTotalPagesNumber(Button)
- boolean decreaseZoomFactor(double)
- boolean increaseZoomFactor(double)
- void updatePagesList()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$SearchService {
# Task<List<PDFView.SearchResult>> createTask()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$SearchService$SearchException {
}
class OracLib.PDFViewFX.skins.PDFViewSkin$SearchTask {
- SearchableDocument document
- String searchText
# List<SearchResult> call()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$PagerService {
- boolean up
+ void setUp(boolean)
# Task<Void> createTask()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$PagerTask {
- boolean up
# Void call()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$MainAreaScrollPane {
- StackPane wrapper
- Pane pane
- Group group
- RenderService mainAreaRenderService
- Rectangle bouncer
- ImageView imageView
- ParallelTransition parallel
- ObjectProperty<Image> image
- void bounceSearchResult()
- void setImage(Image)
- Image getImage()
# void layoutImage()
- void fitWidth(ImageView)
- void fitAll(ImageView)
- void updateScrollbarPolicies()
- boolean isPortrait()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$RenderService {
- boolean thumbnailRenderer
- FloatProperty scale
- IntegerProperty page
- float getScale()
~ FloatProperty scaleProperty()
- void setPage(int)
- int getPage()
~ IntegerProperty pageProperty()
# Task<Image> createTask()
}
class OracLib.PDFViewFX.skins.PDFViewSkin$RenderTask {
- int page
- float scale
- boolean thumbnail
# Image call()
- Image renderPDFPage(int,float)
- void highlightSearchResults(int,float,BufferedImage)
}
class OracLib.PDFViewFX.skins.PDFViewSkin$SearchResultListCell {
- Label pageLabel
- Label matchesLabel
- Label summaryLabel
- ImageView imageView
- RenderService renderService
# void updateItem(PageSearchResult,boolean)
}
class OracLib.PDFViewFX.skins.PDFViewSkin$PdfPageListCell {
- ImageView imageView
- Label pageNumberLabel
- RenderService renderService
# void updateItem(Integer,boolean)
}
class OracLib.PDFViewFX.skins.PDFViewSkin$PageSearchResult {
- int pageNumber
- String searchText
- List<SearchResult> items
+ String getSearchText()
+ int getPageNumber()
+ List<SearchResult> getItems()
+ int compareTo(PageSearchResult)
+ boolean equals(Object)
+ int hashCode()
}
class OracLib.LoginController {
- Label prompt
- TextField username
- PasswordField password
- Button forgotPass
- int clickCount
- int maxClicks
- Main main
+ void setMain(Main)
- void handleLogin(ActionEvent)
- void handleRegister(ActionEvent)
+ void onForgotPass(ActionEvent)
- boolean isValid(String,String)
- boolean isNotValidString(String)
- void onExit()
}
class OracLib.PDFViewFX.PDFView {
- BooleanProperty showThumbnails
- BooleanProperty showToolBar
- BooleanProperty showSearchResults
- BooleanProperty cacheThumbnails
- DoubleProperty maxZoomFactor
- DoubleProperty zoomFactor
- DoubleProperty pageRotation
- IntegerProperty page
- BooleanProperty showAll
- FloatProperty thumbnailPageScale
- FloatProperty pageScale
- DoubleProperty thumbnailSize
- ObjectProperty<Document> document
- StringProperty searchText
- ListProperty<SearchResult> searchResults
- ObjectProperty<SearchResult> selectedSearchResult
- ObjectProperty<Color> searchResultColor
# Skin<?> createDefaultSkin()
+ String getUserAgentStylesheet()
+ boolean isShowThumbnails()
+ BooleanProperty showThumbnailsProperty()
+ void setShowThumbnails(boolean)
+ boolean isShowToolBar()
+ BooleanProperty showToolBarProperty()
+ void setShowToolBar(boolean)
+ boolean isShowSearchResults()
+ BooleanProperty showSearchResultsProperty()
+ void setShowSearchResults(boolean)
+ boolean isCacheThumbnails()
+ BooleanProperty cacheThumbnailsProperty()
+ void setCacheThumbnails(boolean)
+ double getMaxZoomFactor()
+ DoubleProperty maxZoomFactorProperty()
+ void setMaxZoomFactor(double)
+ double getZoomFactor()
+ DoubleProperty zoomFactorProperty()
+ void setZoomFactor(double)
+ double getPageRotation()
+ DoubleProperty pageRotationProperty()
+ void setPageRotation(double)
+ void rotateLeft()
+ void rotateRight()
+ int getPage()
+ IntegerProperty pageProperty()
+ void setPage(int)
+ boolean gotoNextPage()
+ boolean gotoPreviousPage()
+ boolean gotoLastPage()
+ boolean isShowAll()
+ BooleanProperty showAllProperty()
+ void setShowAll(boolean)
+ float getThumbnailPageScale()
+ FloatProperty thumbnailPageScaleProperty()
+ void setThumbnailPageScale(float)
+ float getPageScale()
+ FloatProperty pageScaleProperty()
+ void setPageScale(float)
+ double getThumbnailSize()
+ DoubleProperty thumbnailSizeProperty()
+ void setThumbnailSize(double)
+ ObjectProperty<Document> documentProperty()
+ Document getDocument()
+ void setDocument(Document)
+ String getSearchText()
+ StringProperty searchTextProperty()
+ void setSearchText(String)
+ ListProperty<SearchResult> searchResultsProperty()
+ ObservableList<SearchResult> getSearchResults()
+ void setSearchResults(ObservableList<SearchResult>)
+ ObjectProperty<SearchResult> selectedSearchResultProperty()
+ SearchResult getSelectedSearchResult()
+ void setSelectedSearchResult(SearchResult)
+ ObjectProperty<Color> searchResultColorProperty()
+ Color getSearchResultColor()
+ void setSearchResultColor(Color)
+ void load(File)
+ void load(InputStream)
+ void load(Supplier<Document>)
+ void unload()
}
interface OracLib.PDFViewFX.PDFView$Document {
~ BufferedImage renderPage(int,float)
~ int getNumberOfPages()
~ boolean isLandscape(int)
~ Pageable getPageable()
~ void close()
}
class OracLib.PDFViewFX.PDFView$Document$DocumentProcessingException {
}
interface OracLib.PDFViewFX.PDFView$SearchableDocument {
~ List<SearchResult> getSearchResults(String)
}
class OracLib.PDFViewFX.PDFView$SearchResult {
- String searchText
- String textSnippet
- int pageNumber
- Rectangle2D marker
+ Rectangle2D getMarker()
+ Rectangle2D getScaledMarker(double)
+ String getSearchText()
+ String getTextSnippet()
+ int getPageNumber()
+ int compareTo(SearchResult)
+ boolean equals(Object)
+ int hashCode()
}
class OracLib.UserData {
- int index
- String username
- String password
- String profilePic
- String userBio
- String age
- String book1
- String book2
- String book3
- String book4
- String book5
+ void setUserIndex(int)
+ int getIndex()
+ void setUsername(String)
+ String getUsername()
+ void setPassword(String)
+ String getPassword()
+ void setProfilePic(String)
+ String getProfilePic()
+ void setUserBio(String)
+ String getUserBio()
+ void setAge(String)
+ String getAge()
+ void setBook1(String)
+ String getBook1()
+ void setBook2(String)
+ String getBook2()
+ void setBook3(String)
+ String getBook3()
+ void setBook4(String)
+ String getBook4()
+ void setBook5(String)
+ String getBook5()
}


OracLib.BaseQuote <|-- OracLib.QuoteController
javafx.application.Application <|-- OracLib.Main
OracLib.PDFViewFX.PDFView.SearchableDocument <|.. OracLib.PDFViewFX.PDFBoxDocument
OracLib.LibraryView <|.. OracLib.LibraryController
OracLib.PDFViewFX.skins.SkinBase <|-- OracLib.PDFViewFX.skins.PDFViewSkin
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$SearchService
OracLib.PDFViewFX.skins.Service <|-- OracLib.PDFViewFX.skins.PDFViewSkin$SearchService
OracLib.PDFViewFX.skins.PDFViewSkin$SearchService +.. OracLib.PDFViewFX.skins.PDFViewSkin$SearchService$SearchException
OracLib.PDFViewFX.skins.RuntimeException <|-- OracLib.PDFViewFX.skins.PDFViewSkin$SearchService$SearchException
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$SearchTask
OracLib.PDFViewFX.skins.Task <|-- OracLib.PDFViewFX.skins.PDFViewSkin$SearchTask
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$PagerService
OracLib.PDFViewFX.skins.Service <|-- OracLib.PDFViewFX.skins.PDFViewSkin$PagerService
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$PagerTask
OracLib.PDFViewFX.skins.Task <|-- OracLib.PDFViewFX.skins.PDFViewSkin$PagerTask
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$MainAreaScrollPane
OracLib.PDFViewFX.skins.ScrollPane <|-- OracLib.PDFViewFX.skins.PDFViewSkin$MainAreaScrollPane
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$RenderService
OracLib.PDFViewFX.skins.Service <|-- OracLib.PDFViewFX.skins.PDFViewSkin$RenderService
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$RenderTask
OracLib.PDFViewFX.skins.Task <|-- OracLib.PDFViewFX.skins.PDFViewSkin$RenderTask
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$SearchResultListCell
OracLib.PDFViewFX.skins.ListCell <|-- OracLib.PDFViewFX.skins.PDFViewSkin$SearchResultListCell
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$PdfPageListCell
OracLib.PDFViewFX.skins.ListCell <|-- OracLib.PDFViewFX.skins.PDFViewSkin$PdfPageListCell
OracLib.PDFViewFX.skins.PDFViewSkin +.. OracLib.PDFViewFX.skins.PDFViewSkin$PageSearchResult
OracLib.PDFViewFX.skins.Comparable <|.. OracLib.PDFViewFX.skins.PDFViewSkin$PageSearchResult
javafx.scene.control.Control <|-- OracLib.PDFViewFX.PDFView
OracLib.PDFViewFX.PDFView +.. OracLib.PDFViewFX.PDFView$Document
OracLib.PDFViewFX.PDFView$Document +.. OracLib.PDFViewFX.PDFView$Document$DocumentProcessingException
OracLib.PDFViewFX.RuntimeException <|-- OracLib.PDFViewFX.PDFView$Document$DocumentProcessingException
OracLib.PDFViewFX.PDFView +.. OracLib.PDFViewFX.PDFView$SearchableDocument
OracLib.PDFViewFX.Document <|-- OracLib.PDFViewFX.PDFView$SearchableDocument
OracLib.PDFViewFX.PDFView +.. OracLib.PDFViewFX.PDFView$SearchResult
OracLib.PDFViewFX.Comparable <|.. OracLib.PDFViewFX.PDFView$SearchResult
@enduml